# Generated by Django 4.2.13 on 2024-07-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
