# Generated by Django 4.2.13 on 2024-07-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_name_test_title_remove_question_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='banner_img',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
