# Generated by Django 4.2.13 on 2024-07-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_option_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='test',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
