# Generated by Django 4.2.13 on 2024-08-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_test_public_test_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='banner_img',
        ),
        migrations.AddField(
            model_name='test',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='SkillCert'),
        ),
    ]
