# Generated by Django 4.2.13 on 2024-08-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_test_banner_img_test_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='banner',
            field=models.ImageField(blank=True, default='', upload_to='SkillCert'),
        ),
    ]
