# Generated by Django 4.2.13 on 2024-08-11 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_test_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='score',
            field=models.IntegerField(default=55),
        ),
        migrations.AlterField(
            model_name='testattemptanswer',
            name='test_attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='api.testattempt'),
        ),
    ]
