# Generated by Django 4.2.13 on 2024-10-22 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_testattempt_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testattemptanswer',
            name='test_attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.testattempt'),
        ),
    ]
